Feat 7
jokay03J-V2/projet-fil-rouge pull request #14
Opened 2024-06-05 14:06 UTC by shinjiiiiiii

2024-06-05 14:19 UTC, jokay03J-V2 requested changes

2024-06-05 14:19 UTC, jokay03J-V2 commented on database/factories/CategoryAdviceFactory.php
> +    protected $model = CategoryAdvice::class;
enlève ça sert à rien

2024-06-05 14:19 UTC, jokay03J-V2 commented on database/seeders/AdviceSeeder.php
Fait en sorte de pouvoir démarrer le seeder pour les catégorie et ensuite les conseils dans le _DatabaseSeeder_ directement sinon faut faire plusieurs commandes pour seed la base de donnée

2024-06-05 14:19 UTC, jokay03J-V2 commented on database/seeders/CategoryAdviceSeeder.php
Fait en sorte de pouvoir démarrer le seeder pour les catégorie et ensuite les conseils dans le _DatabaseSeeder_ directement sinon faut faire plusieurs commandes pour seed la base de donnée

2024-06-06 14:16 UTC, jokay03J-V2 approved these changes

2024-06-06 14:17 UTC, Cyberfox206 approved these changes

2024-06-06 14:17 UTC, Cannellespeculos approved these changes

2024-06-06 14:18 UTC, merged